### ISSUE TITLE
Pick Block issue with Pick Block Pro mod (allows to pick blockstates)

### ISSUE THREAD

**Issue by encumber** [AmyMialeeMods/visiblebarriers#26] opened 2023-06-28 15:24 UTC
when using the mod [Pick Block Pro](https://modrinth.com/mod/pick-block-pro) middle clicking while in creative no longer works as it always grabs air instead of what you're looking at/light blocks if picking the sun

**Comment by Sjouwer** [comment] 2023-06-30 17:17
Issue was also posted on my mod: https://github.com/Sjouwer/pick-block-pro/issues/16
I did some testing and found no issues with Pick Block Pro, seems the issue is with Litematica instead:
https://github.com/AmyMialeeMods/visible-barriers/issues/22

**Comment by DeffOSofficial** [comment] 2023-07-05 11:28
I found! The problem is really related to the "litemathic" mod.

Litemathica > Configuration Menu > Hotkeys > pickBlockFirst.
Сhange the assigned "button 3" to your own.

**Comment by AmyMialee** [comment] 2024-01-11 19:46
I think I will close this for now, in the planned rewrite I will likely remove (normal) air support (keeping cave and void air).
If this is still an issue after that rewrite feel free to open a new issue.

**Closed by AmyMialee** 2024-01-11 19:46 UTC
